trigger: none

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Build OK
- stage: Dev
  dependsOn: Build
  jobs:
  - job: DevJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Dev OK
- stage: QA
  dependsOn: Dev
  jobs:
  - job: QAJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo QA OK
- stage: Prod
  dependsOn: QA
  jobs:
  - job: ProdJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Prod OK
