trigger:
- main

pool:
  vmImage: 'ubuntu-22.04'

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt || true
    pip install pytest pytest-cov
  displayName: 'Install deps'

- script: |
    pytest --cov=. --cov-report=xml -q || echo "no tests"
  displayName: 'Run tests'

- script: |
    wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
    unzip -q sonar-scanner-cli-6.2.1.4610-linux-x64.zip
    export PATH=$(pwd)/sonar-scanner-6.2.1.4610-linux-x64/bin:$PATH
    sonar-scanner \
      -Dsonar.organization=reshma-devops1 \
      -Dsonar.projectKey=reshma-devops1_myproject \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.sources=.
  displayName: 'SonarCloud Scan'
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)

# --- NEW OPTIMIZED PART ---
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/*.py
      README.md
      requirements.txt
      azure-pipelines.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy only code files'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop-main'
  displayName: 'Publish Small Artifact'
